export const GET_USER = 'GET_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// for profile
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const GET_ERRORS = 'GET_ERRORS'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const DONE_EDITING_PROFILE = 'DONE_EDITING_PROFILE'

// for drawer
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'
