const POST_ID = 'postID'
const POST_OWNER_ID = 'postOwnerID'
const OWNER_ID = 'owenerID'
const OTHER_USER_ID = 'otherUserID'
const ANY_USER_ID = 'anyUserID'

const POST_ID_TYPE = `${POST_ID}: ID`
const POST_OWNER_ID_TYPE = `${POST_OWNER_ID}: ID`
const OWNER_ID_TYPE = `${OWNER_ID}: ID`
const OTHER_USER_ID_TYPE = `${OTHER_USER_ID}: ID`
const ANY_USER_ID_TYPE = `${ANY_USER_ID}: ID`

export {
	POST_ID,
	POST_OWNER_ID,
	OWNER_ID,
	OTHER_USER_ID,
	ANY_USER_ID,
	POST_ID_TYPE,
	POST_OWNER_ID_TYPE,
	OWNER_ID_TYPE,
	OTHER_USER_ID_TYPE,
	ANY_USER_ID_TYPE,
}
